#!/usr/bin/env bash
#A bash script that terminates a processes
PID=$(ps -ef | grep 4-to_infinity_and_beyond
)

if [ -n "PID" ]; then
	kill "$PID"
	echo "Process have been terminated"
else 
	echo "The process not found"
fi
