#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20. For specific iterations, it should display additional “bad luck” 
MESSAGE=1
while [ $MESSAGE -le 20 ]; do
case $MESSAGE in

4)
	echo "$MESSAGE"
        echo "bad luck from China"
	;;

9)
	echo "$MESSAGE"
        echo "bad luck from Japan"
	;;

17)
 	echo "$MESSAGE"
        echo "bad luck from Italy"
	;;
*)
	echo "$MESSAGE"
   
esac
    MESSAGE=$((MESSAGE + 1))
done


